version: '3.4'
services:
  web:
    # tty: true
    image: my_odoo_14:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
      # - "5678:5678"
      # - "1984:1984"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - /root/repos/enterprise-14.0:/mnt/1
      - /root/repos/smile2impress:/mnt/2
      - /root/repos/S2I-OCA-addons:/mnt/3
      - /root/repos/bank-statement-import:/mnt/4
      - /root/repos/l10n-spain:/mnt/5
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
    command: bash -c "/entrypoint.sh odoo --dev=xml"

  db:
    image: postgres:10
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
  odoo-db-data:
