version: '3.4'
services:
  web:
    tty: true
    image: my_odoo_11:latest
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../../../itprojects/odoo-11.0/mail-addons:/mnt/1
      - ../../../itprojects/odoo-11.0/misc-addons:/mnt/2
      - ../../../itprojects/odoo-11.0/website-addons:/mnt/3
      - ../../../itprojects/odoo-11.0/website:/mnt/4
      - ../../../itprojects/odoo-11.0/access-addons:/mnt/5
      - ../../../itprojects/odoo-11.0/pos-addons:/mnt/6
      - ../../../itprojects/odoo-11.0/odoo/addons/point_of_sale:/usr/lib/python3/dist-packages/odoo/addons/point_of_sale
      - ../../../itprojects/odoo-11.0/odoo/addons/stock:/usr/lib/python3/dist-packages/odoo/addons/stock
      - ../../../itprojects/odoo-11.0/odoo/addons/product:/usr/lib/python3/dist-packages/odoo/addons/product
      - ../../../itprojects/odoo-11.0/odoo/addons/base_import:/usr/lib/python3/dist-packages/odoo/addons/base_import
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
#    command: ['-d', '--log-handler=odoo.addons.queue_job:DEBUG', '--workers=3']
    command: []

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']

volumes:
  odoo-web-data:
  odoo-db-data:
