version: '3.4'
services:
  web:
    tty: true
    image: my_odoo_11:latest
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../../../../lab/shared-11:/mnt/1
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
#    command: ['-d', '--log-handler=odoo.addons.queue_job:DEBUG', '--workers=3']
    command: bash -c "/entrypoint.sh odoo --dev=xml"
    command: bash -c "/entrypoint.sh odoo --dev=xml" -i access_generator,database_cleanup,fgis_parsing,fgis_nps,intero_reload_form,backend_theme,web_clipboard
  #  command: ["-i access_generator,database_cleanup,fgis_parsing,fgis_nps,intero_reload_form,backend_theme,web_clipboard"]

  db:
    image: postgres:10
    ports:
    - "8001:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']

volumes:
  odoo-web-data:
  odoo-db-data:
